/**
 * `WrapperSpec` -> Astro 5+ ラッパーのソース（純関数）。
 *
 * 契約の木はほぼそのまま HTML になる。`{ raw }` は `<slot />`、`{ prop }` のうち
 * children に相当するものは `<slot>{label}</slot>`（子が無ければ prop がフォールバック）。
 * CSS は `.astro` の `<style is:global>` ではなく integration が注入する（重複を避ける）。
 */
import type { WrapperSpec } from './common.js'
import { childrenTextOf, typeText } from './common.js'
import type { Dialect } from './markup-lang.js'
import { renderTree } from './markup-lang.js'
import type { GeneratedFile } from './react.js'

const HEADER = '// generated by tools/cem — do not edit（`bun run gen`）'

const dialect: Dialect = {
  attr: (name, expression) => `${name}={${expression}}`,
  text: (prop, isChildren) => (isChildren ? `<slot>{${prop}}</slot>` : `{${prop}}`),
  // 既定 slot は `children`。名前つきは `<slot name="…" />`（利用側は `slot="…"` で渡す）
  raw: (name) => (name === 'children' ? '<slot />' : `<slot name="${name}" />`),
}

const componentFile = (spec: WrapperSpec): GeneratedFile => {
  const childrenText = childrenTextOf(spec)
  const visible = spec.markupProps.filter((markupProp) => markupProp.kind !== 'raw')
  const propsType = [
    'type Props = {',
    ...visible.map(
      (markupProp) =>
        `  ${markupProp.name}?: ${markupProp.kind === 'attr' ? typeText(markupProp.type) : 'string'}`,
    ),
    '  class?: string',
    '}',
  ]
  const names = [...visible.map((markupProp) => markupProp.name), 'class: className']
  return {
    // ADR-0009: experimental は `@rimltempest/riml-ds-astro/experimental/<name>.astro` から配る
    path: `${spec.status === 'experimental' ? 'experimental/' : ''}${spec.name}.astro`,
    content: `${[
      '---',
      HEADER,
      ...(spec.namedTypes.length > 0
        ? [
            `import type { ${spec.namedTypes.join(', ')} } from '@rimltempest/riml-ds-elements/${spec.subpath}'`,
          ]
        : []),
      '',
      ...propsType,
      '',
      `const { ${names.join(', ')} } = Astro.props`,
      ...(spec.idFallback === undefined ? [] : [`const controlId = id ?? ${spec.idFallback}`]),
      '---',
      '',
      renderTree(spec, dialect, spec.contract?.tree ?? { text: '' }, childrenText, 0, true),
    ].join('\n')}\n`,
  }
}

export const astroFiles = (specs: readonly WrapperSpec[]): readonly GeneratedFile[] =>
  specs.filter((spec) => spec.contract !== undefined).map(componentFile)
