/**
 * `WrapperSpec` -> React ラッパーのソース（純関数）。ADR-0012 §5。
 *
 * - 既定 export（`<name>.tsx`）は**マークアップ契約の木をそのまま JSX にしただけ**の部品。
 *   `'use client'` を付けないので RSC / SSR から描け、JS 無しでも同じ HTML が出る。
 * - `client/<name>.tsx` は `'use client'` 付き。`rd-*` イベント（React の合成イベントに載らない）を
 *   `addEventListener` で受け、ティア A の controlled は `useLayoutEffect` でネイティブ要素に書き戻す。
 * - `@lit/react` は使わない。いまの部品はどれもプリミティブな属性しか渡さず、React 19 が素で扱える。
 *   Lit を React パッケージに引き込まずに済む（サイズ予算）。オブジェクト/配列のプロパティを渡す
 *   部品が出たらそこだけ `createComponent` を足す（ADR-0002 / ADR-0012 §5）。
 */
import type { AttrType, MarkupNode, MarkupProp, WrapperSpec } from './common.js'

export type GeneratedFile = { readonly path: string; readonly content: string }

const HEADER = '// generated by tools/cem — do not edit（`bun run gen`）'

const PRINT_WIDTH = 100

/** 内容を持たない要素。JSX では自己閉じにする */
const VOID_TAGS: ReadonlySet<string> = new Set([
  'area',
  'base',
  'br',
  'col',
  'embed',
  'hr',
  'img',
  'input',
  'link',
  'meta',
  'source',
  'track',
  'wbr',
])

/** ネイティブ要素だけ。HTML の綴り -> JSX の綴り */
const REACT_ATTR: Readonly<Record<string, string>> = {
  autocomplete: 'autoComplete',
  autofocus: 'autoFocus',
  class: 'className',
  crossorigin: 'crossOrigin',
  enterkeyhint: 'enterKeyHint',
  for: 'htmlFor',
  inputmode: 'inputMode',
  maxlength: 'maxLength',
  minlength: 'minLength',
  novalidate: 'noValidate',
  readonly: 'readOnly',
  spellcheck: 'spellCheck',
  tabindex: 'tabIndex',
}

const FORM_CONTROLS: ReadonlySet<string> = new Set(['input', 'textarea', 'select'])

const DOM_TYPE: Readonly<Record<string, string>> = {
  input: 'HTMLInputElement',
  select: 'HTMLSelectElement',
  textarea: 'HTMLTextAreaElement',
}

const isCustomTag = (tag: string): boolean => tag.includes('-')

const typeText = (type: AttrType): string => {
  if (typeof type === 'string') {
    return type
  }
  return 'union' in type ? type.union.map((value) => `'${value}'`).join(' | ') : type.named
}

/** React の綴りに直す。`value` はフォーム部品では uncontrolled の `defaultValue` に写す */
const reactAttrName = (tag: string, attr: string): string => {
  if (isCustomTag(tag)) {
    return attr
  }
  if (attr === 'value' && FORM_CONTROLS.has(tag)) {
    return 'defaultValue'
  }
  return REACT_ATTR[attr] ?? attr
}

const indent = (depth: number): string => '  '.repeat(depth)

type Context = {
  readonly spec: WrapperSpec
  /** `{ prop }` が children に置き換わる prop 名（button の `label`） */
  readonly childrenText: string | undefined
}

const propType = (markupProp: MarkupProp): string =>
  markupProp.kind === 'attr' ? typeText(markupProp.type) : 'ReactNode'

/** `$id` を `controlId`（`id ?? name`）に読み替える */
const propRef = (spec: WrapperSpec, name: string): string =>
  name === 'id' && spec.idFallback !== undefined ? 'controlId' : name

const attrExpression = (context: Context, value: string | boolean): string => {
  if (typeof value === 'boolean') {
    return value ? '' : '={false}'
  }
  if (!value.startsWith('$')) {
    return `="${value}"`
  }
  const name = value.slice(1)
  const declared = context.spec.markupProps.find((item) => item.name === name)
  const reference = propRef(context.spec, name)
  return declared?.type === 'boolean' ? `={${reference} || undefined}` : `={${reference}}`
}

const attrPairs = (
  context: Context,
  node: Extract<MarkupNode, { tag: string }>,
  root: boolean,
): readonly string[] => {
  const own = Object.entries(node.attrs ?? {}).map(
    ([attr, value]) => `${reactAttrName(node.tag, attr)}${attrExpression(context, value)}`,
  )
  const slot = node.slot === undefined ? [] : [`slot="${node.slot}"`]
  const handlers =
    !root && context.spec.controlTag === node.tag && FORM_CONTROLS.has(node.tag)
      ? ['onInput={onInput}', 'onChange={onChange}', 'onBlur={onBlur}']
      : []
  return root
    ? ['ref={ref}', ...slot, ...own, 'className={className}']
    : [...slot, ...own, ...handlers]
}

const inlineChild = (context: Context, node: MarkupNode): string | undefined => {
  if ('text' in node) {
    return node.text
  }
  if ('prop' in node) {
    return context.childrenText === node.prop ? `{children ?? ${node.prop}}` : `{${node.prop}}`
  }
  if ('raw' in node) {
    return `{${node.raw.startsWith('$') ? node.raw.slice(1) : node.raw}}`
  }
  return undefined
}

const renderNode = (context: Context, node: MarkupNode, depth: number, root: boolean): string => {
  const pad = indent(depth)
  const inline = inlineChild(context, node)
  if (inline !== undefined) {
    return `${pad}${inline}`
  }
  if (!('tag' in node)) {
    return ''
  }
  const pairs = attrPairs(context, node, root)
  const children = node.children ?? []
  const selfClosing = VOID_TAGS.has(node.tag) || children.length === 0
  const open = `<${node.tag}${pairs.map((pair) => ` ${pair}`).join('')}`
  const inlineChildren = children.map((child) => inlineChild(context, child))
  const allInline = inlineChildren.every((child) => child !== undefined)
  const oneLine = selfClosing
    ? `${pad}${open} />`
    : `${pad}${open}>${inlineChildren.join('')}</${node.tag}>`
  if ((selfClosing || allInline) && oneLine.length <= PRINT_WIDTH) {
    return oneLine
  }
  const openLines =
    `${pad}${open}`.length + (selfClosing ? 3 : 1) <= PRINT_WIDTH
      ? [`${pad}${open}${selfClosing ? ' />' : '>'}`]
      : [
          `${pad}<${node.tag}`,
          ...pairs.map((pair) => `${pad}  ${pair}`),
          `${pad}${selfClosing ? '/>' : '>'}`,
        ]
  if (selfClosing) {
    return openLines.join('\n')
  }
  return [
    ...openLines,
    ...children.map((child) => renderNode(context, child, depth + 1, false)),
    `${pad}</${node.tag}>`,
  ].join('\n')
}

/** 契約の木で `controlTag` の直下にある `{ prop }`。React ではそこが children になる */
const childrenTextOf = (spec: WrapperSpec): string | undefined => {
  const visit = (node: MarkupNode): string | undefined => {
    if (!('tag' in node)) {
      return undefined
    }
    if (node.tag === spec.controlTag) {
      const text = (node.children ?? []).find((child) => 'prop' in child)
      return text !== undefined && 'prop' in text ? text.prop : undefined
    }
    for (const child of node.children ?? []) {
      const found = visit(child)
      if (found !== undefined) {
        return found
      }
    }
    return undefined
  }
  return spec.contract === undefined ? undefined : visit(spec.contract.tree)
}

const controlHandlers = (spec: WrapperSpec): readonly string[] =>
  spec.pe === 'A' && FORM_CONTROLS.has(spec.controlTag ?? '')
    ? ['onInput', 'onChange', 'onBlur']
    : []

const handlerType = (spec: WrapperSpec, handler: string): string => {
  const dom = DOM_TYPE[spec.controlTag ?? ''] ?? 'HTMLElement'
  return handler === 'onBlur'
    ? `(event: FocusEvent<${dom}>) => void`
    : `(event: FormEvent<${dom}>) => void`
}

const paramList = (prefix: string, names: readonly string[], suffix: string): string => {
  const oneLine = `${prefix}({ ${names.join(', ')} }${suffix}`
  if (oneLine.length <= PRINT_WIDTH) {
    return oneLine
  }
  // rest 要素（`...rest`）は必ず最後で、後ろにカンマを置けない
  const lines = names.map((name) => (name.startsWith('...') ? `  ${name}` : `  ${name},`))
  return [`${prefix}({`, ...lines, `}${suffix}`].join('\n')
}

const markupFile = (spec: WrapperSpec): GeneratedFile => {
  const childrenText = childrenTextOf(spec)
  const context: Context = { spec, childrenText }
  const handlers = controlHandlers(spec)
  const hasRawChildren = spec.markupProps.some((markupProp) => markupProp.kind === 'raw')
  const extraChildren = childrenText !== undefined && !hasRawChildren
  const reactTypes = [
    'ReactNode',
    'Ref',
    ...(handlers.length > 0 ? ['FocusEvent', 'FormEvent'] : []),
  ]
  const imports = [
    `import type { ${reactTypes.toSorted().join(', ')} } from 'react'`,
    ...(spec.namedTypes.length > 0
      ? [
          `import type { ${spec.namedTypes.join(', ')} } from '@rimltempest/riml-ds-elements/${spec.name}'`,
        ]
      : []),
  ]
  const typeLines = [
    ...spec.markupProps.map(
      (markupProp) =>
        `  readonly ${markupProp.name}${markupProp.optional ? '?' : ''}: ${propType(markupProp)}`,
    ),
    ...(extraChildren ? ['  readonly children?: ReactNode'] : []),
    '  readonly className?: string',
    '  readonly ref?: Ref<HTMLElement>',
    ...handlers.map((handler) => `  readonly ${handler}?: ${handlerType(spec, handler)}`),
  ]
  const names = [
    ...spec.markupProps.map((markupProp) => markupProp.name),
    ...(extraChildren ? ['children'] : []),
    'className',
    'ref',
    ...handlers,
  ]
  const tree = spec.contract?.tree ?? { text: '' }
  const body =
    spec.idFallback === undefined
      ? [
          paramList(
            `export const ${spec.pascal} = `,
            names,
            `: ${spec.pascal}Props): ReactNode => (`,
          ),
          renderNode(context, tree, 1, true),
          ')',
        ]
      : [
          paramList(
            `export const ${spec.pascal} = `,
            names,
            `: ${spec.pascal}Props): ReactNode => {`,
          ),
          '  // `id` を渡さなければ `name` を使う（RSC で使えるよう hook を使わない）',
          `  const controlId = id ?? ${spec.idFallback}`,
          '  return (',
          renderNode(context, tree, 2, true),
          '  )',
          '}',
        ]
  return {
    path: `${spec.name}.tsx`,
    content: `${[
      HEADER,
      ...imports,
      '',
      `export type ${spec.pascal}Props = {`,
      ...typeLines,
      '}',
      '',
      ...body,
    ].join('\n')}\n`,
  }
}

const INTERNAL = `'use client'
${HEADER}
import { useEffect } from 'react'
import type { Ref, RefObject } from 'react'

/** \`rd-*\` は React の合成イベントに載らないので addEventListener で受ける */
export const useRdEvent = <Detail>(
  host: RefObject<HTMLElement | null>,
  type: string,
  handler: ((event: CustomEvent<Detail>) => void) | undefined,
): void => {
  useEffect(() => {
    const element = host.current
    if (element === null || handler === undefined) {
      return undefined
    }
    const listener: EventListener = (event) => {
      if (event instanceof CustomEvent) {
        handler(event)
      }
    }
    element.addEventListener(type, listener)
    return () => element.removeEventListener(type, listener)
  }, [host, type, handler])
}

/** 利用側の ref にホスト要素を渡す（内部の ref と両立させる） */
export const useHostRef = (
  host: RefObject<HTMLElement | null>,
  ref: Ref<HTMLElement> | undefined,
): void => {
  useEffect(() => {
    if (typeof ref === 'function') {
      ref(host.current)
      return () => {
        ref(null)
      }
    }
    if (ref === null || ref === undefined) {
      return undefined
    }
    ref.current = host.current
    return () => {
      ref.current = null
    }
  })
}
`

const clientFile = (spec: WrapperSpec): GeneratedFile => {
  const controlled = spec.pe === 'A' && FORM_CONTROLS.has(spec.controlTag ?? '')
  const helpers = [...(spec.events.length > 0 ? ['useRdEvent'] : []), 'useHostRef'].toSorted()
  const hooks = ['useRef', ...(controlled ? ['useLayoutEffect'] : [])].toSorted()
  const markup = spec.contract !== undefined
  const imports = [
    `import { ${hooks.join(', ')} } from 'react'`,
    `import type { ReactNode, Ref } from 'react'`,
    ...(markup
      ? [
          `import { ${spec.pascal} as ${spec.pascal}Markup } from '../${spec.name}.js'`,
          `import type { ${spec.pascal}Props } from '../${spec.name}.js'`,
        ]
      : []),
    `import { ${helpers.join(', ')} } from './internal.js'`,
  ]
  const typeLines = [
    `export type ${spec.pascal}ClientProps = ${markup ? `Omit<${spec.pascal}Props, 'ref'> & {` : '{'}`,
    ...(controlled ? ['  readonly value?: string'] : []),
    ...(markup ? [] : ['  readonly className?: string']),
    ...spec.events.map((event) => `  readonly ${event.prop}?: (event: ${event.detail}) => void`),
    '  readonly ref?: Ref<HTMLElement>',
    '}',
  ]
  const names = [
    ...(controlled ? ['value', 'defaultValue'] : []),
    ...spec.events.map((event) => event.prop),
    'ref',
    ...(markup ? ['...rest'] : ['className']),
  ]
  const resync = controlled
    ? [
        '  // controlled: 親が値を更新しなければ描画直後に書き戻す（ADR-0012 §5。<input> と同じ意味論）',
        '  useLayoutEffect(() => {',
        `    const control = host.current?.querySelector('${spec.controlTag}') ?? null`,
        '    if (value !== undefined && control !== null && control.value !== value) {',
        '      control.value = value',
        '    }',
        '  })',
      ]
    : []
  const element = markup
    ? `  return <${spec.pascal}Markup ref={host}${controlled ? ' defaultValue={value ?? defaultValue}' : ''} {...rest} />`
    : `  return <${spec.tag} ref={host} className={className} />`
  return {
    path: `client/${spec.name}.tsx`,
    content: `${[
      `'use client'`,
      HEADER,
      ...imports,
      '',
      ...typeLines,
      '',
      paramList(
        `export const ${spec.pascal} = `,
        names,
        `: ${spec.pascal}ClientProps): ReactNode => {`,
      ),
      '  const host = useRef<HTMLElement | null>(null)',
      ...resync,
      ...spec.events.map((event) => `  useRdEvent(host, '${event.name}', ${event.prop})`),
      '  useHostRef(host, ref)',
      element,
      '}',
    ].join('\n')}\n`,
  }
}

const jsxFile = (specs: readonly WrapperSpec[]): GeneratedFile => {
  const imports = specs.flatMap((spec) =>
    spec.namedTypes.length === 0
      ? []
      : [
          `import type { ${spec.namedTypes.join(', ')} } from '@rimltempest/riml-ds-elements/${spec.name}'`,
        ],
  )
  const rows = specs.map((spec) => {
    const own =
      spec.attrs.length === 0
        ? 'Record<string, never>'
        : `{ ${spec.attrs.map((attr) => `${attr.name}?: ${typeText(attr.type)}`).join('; ')} }`
    return `      '${spec.tag}': RdElementAttrs<${own}>`
  })
  return {
    path: 'jsx.ts',
    content: `${[
      HEADER,
      `import type { DetailedHTMLProps, HTMLAttributes } from 'react'`,
      ...imports,
      '',
      '/** `<rd-*>` を JSX に直接書くときの型。部品（`RdButton` など）を使うだけなら要らない */',
      'type RdElementAttrs<Own> = DetailedHTMLProps<HTMLAttributes<HTMLElement>, HTMLElement> & Own',
      '',
      `declare module 'react' {`,
      '  namespace JSX {',
      '    interface IntrinsicElements {',
      ...rows,
      '    }',
      '  }',
      '}',
      '',
      'export {}',
    ].join('\n')}\n`,
  }
}

export const reactFiles = (specs: readonly WrapperSpec[]): readonly GeneratedFile[] => {
  const withMarkup = specs.filter((spec) => spec.contract !== undefined)
  return [
    ...withMarkup.map(markupFile),
    { path: 'client/internal.ts', content: INTERNAL },
    ...specs.map(clientFile),
    jsxFile(specs),
    {
      path: 'index.ts',
      content: `${[
        HEADER,
        `import './jsx.js'`,
        '',
        ...withMarkup.flatMap((spec) => [
          `export { ${spec.pascal} } from './${spec.name}.js'`,
          `export type { ${spec.pascal}Props } from './${spec.name}.js'`,
        ]),
      ].join('\n')}\n`,
    },
    {
      path: 'client.ts',
      content: `${[
        `'use client'`,
        HEADER,
        '',
        ...specs.flatMap((spec) => [
          `export { ${spec.pascal} } from './client/${spec.name}.js'`,
          `export type { ${spec.pascal}ClientProps } from './client/${spec.name}.js'`,
        ]),
      ].join('\n')}\n`,
    },
  ]
}
