/**
 * `WrapperSpec` -> Svelte 5 ラッパーのソース（純関数）。
 *
 * `.svelte` はビルドせずそのまま配る（`svelte` フィールドが `src` を指す）。TypeScript を
 * 使わない素の `<script>` にしてあるので、利用側に preprocess を強制しない。
 * `<rd-*>` を直接書くときの型は `svelteHTML` の拡張（`elements.d.ts`）が受ける。
 */
import type { WrapperSpec } from './common.js'
import { childrenTextOf, typeText } from './common.js'
import type { Dialect } from './markup-lang.js'
import { renderTree } from './markup-lang.js'
import type { GeneratedFile } from './react.js'

const HEADER = '<!-- generated by tools/cem — do not edit（`bun run gen`） -->'
const TS_HEADER = '// generated by tools/cem — do not edit（`bun run gen`）'

const dialect: Dialect = {
  attr: (name, expression, shorthand) =>
    shorthand ? `{${expression}}` : `${name}={${expression}}`,
  customAttr: (name, prop, isBoolean) => {
    const entry = name === prop ? `{ ${name} }` : `{ ${name}: ${prop} }`
    return isBoolean
      ? `{...(${prop} === true ? ${entry} : {})}`
      : `{...(${prop} === undefined ? {} : ${entry})}`
  },
  text: (prop, isChildren) =>
    isChildren ? `{#if children}{@render children()}{:else}{${prop}}{/if}` : `{${prop}}`,
  raw: () => '{@render children()}',
}

const componentFile = (spec: WrapperSpec): GeneratedFile => {
  const childrenText = childrenTextOf(spec)
  const hasRaw = spec.markupProps.some((markupProp) => markupProp.kind === 'raw')
  const names = [
    ...spec.markupProps.map((markupProp) => markupProp.name),
    ...(childrenText !== undefined && !hasRaw ? ['children'] : []),
    'class: className',
  ]
  const script = [
    '<script>',
    `  let { ${names.join(', ')} } = $props()`,
    // `$derived` にしないと prop が変わっても更新されない（state_referenced_locally）
    ...(spec.idFallback === undefined
      ? []
      : [`  const controlId = $derived(id ?? ${spec.idFallback})`]),
    '</script>',
  ]
  return {
    path: `${spec.name}.svelte`,
    content: `${[
      HEADER,
      ...script,
      '',
      renderTree(spec, dialect, spec.contract?.tree ?? { text: '' }, childrenText, 0, true),
    ].join('\n')}\n`,
  }
}

/** グローバルな `.d.ts` にするため、名前つきの型は `import('...')` で参照する */
const inlineType = (spec: WrapperSpec, text: string): string =>
  spec.namedTypes.includes(text)
    ? `import('@rimltempest/riml-ds-elements/${spec.subpath}').${text}`
    : text

const elementsFile = (specs: readonly WrapperSpec[]): GeneratedFile => {
  const rows = specs.flatMap((spec) => {
    const attrs = spec.attrs.map(
      (attr) => `      ${attr.name}?: ${inlineType(spec, typeText(attr.type))}`,
    )
    const events = spec.events.map(
      (event) => `      '${event.name.replace('rd-', 'onrd-')}'?: (event: ${event.detail}) => void`,
    )
    return [`    '${spec.tag}': {`, ...attrs, ...events, '    }']
  })
  return {
    path: 'elements.d.ts',
    content: `${[
      TS_HEADER,
      '',
      '/** `<rd-*>` を Svelte のテンプレートに直接書くときの型。イベントは `onrd-*` で受ける */',
      'declare namespace svelteHTML {',
      '  interface IntrinsicElements {',
      ...rows,
      '  }',
      '}',
    ].join('\n')}\n`,
  }
}

const indexFile = (path: string, specs: readonly WrapperSpec[]): GeneratedFile => ({
  path,
  content: `${[
    TS_HEADER,
    ...specs.map((spec) => `export { default as ${spec.pascal} } from './${spec.name}.svelte'`),
  ].join('\n')}\n`,
})

export const svelteFiles = (specs: readonly WrapperSpec[]): readonly GeneratedFile[] => {
  const withMarkup = specs.filter((spec) => spec.contract !== undefined)
  return [
    ...withMarkup.map(componentFile),
    elementsFile(specs),
    // ADR-0009: experimental は `@rimltempest/riml-ds-svelte/experimental` からしか出さない
    indexFile(
      'index.js',
      withMarkup.filter((spec) => spec.status !== 'experimental'),
    ),
    indexFile(
      'experimental.js',
      withMarkup.filter((spec) => spec.status === 'experimental'),
    ),
  ]
}
