/**
 * `WrapperSpec` -> Vue 3.5 ラッパーのソース（純関数）。
 *
 * SFC を使わず `defineComponent` + `h()` で契約の木を描く。ビルドが `tsgo` だけで済み、
 * 利用側の Vue バージョンに縛られない。ティア A のフォーム部品は `modelValue` /
 * `update:modelValue` を受けるので `v-model` がそのまま効く（skills/riml-ds §3）。
 * `<rd-*>` をテンプレートに直接書く場合は `IntrinsicElementAttributes` の拡張が受ける
 * （`isCustomElement` の設定は利用側。ADR-0002）。
 */
import type { MarkupNode, WrapperSpec } from './common.js'
import { childrenTextOf, typeText } from './common.js'
import type { GeneratedFile } from './react.js'

const HEADER = '// generated by tools/cem — do not edit（`bun run gen`）'

const FORM_CONTROLS: ReadonlySet<string> = new Set(['input', 'textarea', 'select'])

const propsType = (spec: WrapperSpec, modelled: boolean): readonly string[] => [
  `export type ${spec.pascal}Props = {`,
  ...spec.markupProps.flatMap((markupProp) =>
    markupProp.kind === 'raw'
      ? []
      : [`  readonly ${markupProp.name}?: ${typeText(markupProp.type)}`],
  ),
  ...(modelled ? ['  readonly modelValue?: string'] : []),
  '}',
]

const propNames = (spec: WrapperSpec, modelled: boolean): readonly string[] => [
  ...spec.markupProps.flatMap((markupProp) => (markupProp.kind === 'raw' ? [] : [markupProp.name])),
  ...(modelled ? ['modelValue'] : []),
]

/** 属性値の式。`$prop` は `props.prop`、boolean は未指定なら属性ごと落とす */
const attrValue = (spec: WrapperSpec, value: string | boolean, modelled: boolean): string => {
  if (typeof value === 'boolean') {
    return String(value)
  }
  if (!value.startsWith('$')) {
    return `'${value}'`
  }
  const name = value.slice(1)
  if (name === 'id' && spec.idFallback !== undefined) {
    return 'controlId'
  }
  if (name === 'defaultValue' && modelled) {
    return 'props.modelValue ?? props.defaultValue'
  }
  const declared = spec.markupProps.find((item) => item.name === name)
  return declared?.type === 'boolean' ? `props.${name} || undefined` : `props.${name}`
}

const nodeSource = (
  spec: WrapperSpec,
  node: MarkupNode,
  childrenText: string | undefined,
  modelled: boolean,
  depth: number,
): string => {
  const pad = '  '.repeat(depth)
  if ('text' in node) {
    return `${pad}'${node.text}'`
  }
  if ('prop' in node) {
    return `${pad}${node.prop === childrenText ? `slots['default']?.() ?? props.${node.prop}` : `props.${node.prop}`}`
  }
  if ('raw' in node) {
    return `${pad}slots['default']?.()`
  }
  const entries = Object.entries(node.attrs ?? {}).map(
    ([attr, value]) => `${attr}: ${attrValue(spec, value, modelled)}`,
  )
  const slot = node.slot === undefined ? [] : [`slot: '${node.slot}'`]
  const handler =
    spec.controlTag === node.tag && modelled && FORM_CONTROLS.has(node.tag) ? ['onInput'] : []
  const props = [...slot, ...entries, ...handler]
  const propsSource = props.length === 0 ? 'null' : `{ ${props.join(', ')} }`
  const children = node.children ?? []
  if (children.length === 0) {
    return `${pad}h('${node.tag}', ${propsSource})`
  }
  const inlineChildren = children.every((child) => !('tag' in child))
  if (inlineChildren && children.length === 1) {
    const only = nodeSource(spec, children[0] ?? { text: '' }, childrenText, modelled, 0)
    return `${pad}h('${node.tag}', ${propsSource}, ${only})`
  }
  return [
    `${pad}h('${node.tag}', ${propsSource}, [`,
    ...children.map((child) => `${nodeSource(spec, child, childrenText, modelled, depth + 1)},`),
    `${pad}])`,
  ].join('\n')
}

const componentFile = (spec: WrapperSpec): GeneratedFile => {
  const childrenText = childrenTextOf(spec)
  const hasSlots =
    childrenText !== undefined || spec.markupProps.some((item) => item.kind === 'raw')
  const modelled = spec.pe === 'A' && FORM_CONTROLS.has(spec.controlTag ?? '')
  const context = [...(hasSlots ? ['slots'] : []), ...(modelled ? ['emit'] : [])]
  const param = context.length === 0 ? '' : `, { ${context.join(', ')} }`
  const tree = nodeSource(
    spec,
    spec.contract?.tree ?? { text: '' },
    childrenText,
    modelled,
    modelled ? 3 : 2,
  )
  const setupLines = modelled
    ? [
        `  (props: ${spec.pascal}Props${param}) => {`,
        '    const onInput = (event: Event): void => {',
        `      if (event.target instanceof HTMLInputElement) {`,
        `        emit('update:modelValue', event.target.value)`,
        '      }',
        '    }',
        '    return () => {',
        ...(spec.idFallback === undefined
          ? []
          : [`      const controlId = props.id ?? props.${spec.idFallback}`]),
        `      return ${tree.trimStart()}`,
        '    }',
        '  },',
      ]
    : [`  (props: ${spec.pascal}Props${param}) => () =>`, `${tree},`]
  const options = [
    '  {',
    `    name: '${spec.pascal}',`,
    `    props: [${propNames(spec, modelled)
      .map((name) => `'${name}'`)
      .join(', ')}],`,
    ...(modelled ? [`    emits: ['update:modelValue'],`] : []),
    '  },',
  ]
  return {
    path: `${spec.name}.ts`,
    content: `${[
      HEADER,
      `import { defineComponent, h } from 'vue'`,
      ...(spec.namedTypes.length > 0
        ? [
            `import type { ${spec.namedTypes.join(', ')} } from '@rimltempest/riml-ds-elements/${spec.name}'`,
          ]
        : []),
      '',
      ...propsType(spec, modelled),
      '',
      `export const ${spec.pascal} = defineComponent(`,
      ...setupLines,
      ...options,
      ')',
    ].join('\n')}\n`,
  }
}

const elementsFile = (specs: readonly WrapperSpec[]): GeneratedFile => {
  const imports = specs.flatMap((spec) =>
    spec.namedTypes.length === 0
      ? []
      : [
          `import type { ${spec.namedTypes.join(', ')} } from '@rimltempest/riml-ds-elements/${spec.name}'`,
        ],
  )
  const withMarkup = specs.filter((spec) => spec.contract !== undefined)
  return {
    path: 'elements.ts',
    content: `${[
      HEADER,
      ...imports,
      '',
      `declare module 'vue' {`,
      '  interface GlobalComponents {',
      ...withMarkup.map(
        (spec) => `    ${spec.pascal}: typeof import('./${spec.name}.js')['${spec.pascal}']`,
      ),
      '  }',
      '  /** `<rd-*>` をテンプレートに直接書くときの属性（`isCustomElement` は利用側の設定） */',
      '  interface IntrinsicElementAttributes {',
      ...specs.map((spec) => {
        const own =
          spec.attrs.length === 0
            ? 'Record<string, never>'
            : `{ ${spec.attrs.map((attr) => `${attr.name}?: ${typeText(attr.type)}`).join('; ')} }`
        return `    '${spec.tag}': ${own}`
      }),
      '  }',
      '}',
      '',
      'export {}',
    ].join('\n')}\n`,
  }
}

export const vueFiles = (specs: readonly WrapperSpec[]): readonly GeneratedFile[] => {
  const withMarkup = specs.filter((spec) => spec.contract !== undefined)
  return [
    ...withMarkup.map(componentFile),
    elementsFile(specs),
    {
      path: 'index.ts',
      content: `${[
        HEADER,
        `import './elements.js'`,
        ...withMarkup.map((spec) => `import { ${spec.pascal} } from './${spec.name}.js'`),
        '',
        ...withMarkup.map((spec) => `export type { ${spec.pascal}Props } from './${spec.name}.js'`),
        `export { ${withMarkup.map((spec) => spec.pascal).join(', ')} }`,
        '',
        '/** プラグインが `app.component()` で登録する全部品 */',
        `export const rdComponents = { ${withMarkup.map((spec) => spec.pascal).join(', ')} }`,
      ].join('\n')}\n`,
    },
  ]
}
