/**
 * `WrapperSpec` -> Vue 3.5 ラッパーのソース（純関数）。
 *
 * SFC を使わず `defineComponent` + `h()` で契約の木を描く。ビルドが `tsgo` だけで済み、
 * 利用側の Vue バージョンに縛られない。ティア A のフォーム部品は `modelValue` /
 * `update:modelValue` を受けるので `v-model` がそのまま効く（skills/riml-ds §3）。
 * `<rd-*>` をテンプレートに直接書く場合は `IntrinsicElementAttributes` の拡張が受ける
 * （`isCustomElement` の設定は利用側。ADR-0002）。
 */
import type { MarkupNode, WrapperSpec } from './common.js'
import { childrenTextOf, objectKey, typeText } from './common.js'
import type { GeneratedFile } from './react.js'

const HEADER = '// generated by tools/cem — do not edit（`bun run gen`）'

const FORM_CONTROLS: ReadonlySet<string> = new Set(['input', 'textarea', 'select'])

const propsType = (spec: WrapperSpec, modelled: boolean): readonly string[] => [
  `export type ${spec.pascal}Props = {`,
  ...spec.markupProps.flatMap((markupProp) =>
    markupProp.kind === 'raw'
      ? []
      : [`  readonly ${markupProp.name}?: ${typeText(markupProp.type)}`],
  ),
  ...(modelled ? ['  readonly modelValue?: string'] : []),
  '}',
]

const propNames = (spec: WrapperSpec, modelled: boolean): readonly string[] => [
  ...spec.markupProps.flatMap((markupProp) => (markupProp.kind === 'raw' ? [] : [markupProp.name])),
  ...(modelled ? ['modelValue'] : []),
]

/** 属性値の式。`$prop` は `props.prop`、boolean は未指定なら属性ごと落とす */
const attrValue = (spec: WrapperSpec, value: string | boolean, modelled: boolean): string => {
  if (typeof value === 'boolean') {
    return String(value)
  }
  if (!value.startsWith('$')) {
    return `'${value}'`
  }
  const name = value.slice(1)
  if (name === 'id' && spec.idFallback !== undefined) {
    return 'controlId'
  }
  if (name === 'defaultValue' && modelled) {
    return 'props.modelValue ?? props.defaultValue'
  }
  const declared = spec.markupProps.find((item) => item.name === name)
  return declared?.type === 'boolean' ? `props.${name} || undefined` : `props.${name}`
}

/**
 * custom element では**キーがある**だけで Vue がプロパティを書く（`patchDOMProp`）。
 * `dismissible: undefined` は要素の既定値（`true`）を潰すので、未指定ならキーごと落とす。
 */
const customSpread = (
  spec: WrapperSpec,
  attr: string,
  value: string | boolean,
  modelled: boolean,
): readonly string[] => {
  const key = objectKey(attr)
  if (typeof value === 'boolean' || !value.startsWith('$')) {
    return [`${key}: ${attrValue(spec, value, modelled)}`]
  }
  const name = value.slice(1)
  const declared = spec.markupProps.find((item) => item.name === name)
  return declared?.type === 'boolean'
    ? [`...(props.${name} === true ? { ${key}: true } : {})`]
    : [`...(props.${name} === undefined ? {} : { ${key}: props.${name} })`]
}

const nodeSource = (
  spec: WrapperSpec,
  node: MarkupNode,
  childrenText: string | undefined,
  modelled: boolean,
  depth: number,
): string => {
  const pad = '  '.repeat(depth)
  if ('text' in node) {
    return `${pad}'${node.text}'`
  }
  if ('prop' in node) {
    return `${pad}${node.prop === childrenText ? `slots['default']?.() ?? props.${node.prop}` : `props.${node.prop}`}`
  }
  if ('raw' in node) {
    // 既定 slot は `children`。名前つきは `<template #trigger>` で受ける
    const name = node.raw.startsWith('$') ? node.raw.slice(1) : node.raw
    return `${pad}slots['${name === 'children' ? 'default' : name}']?.()`
  }
  const custom = node.tag.includes('-')
  const entries = Object.entries(node.attrs ?? {}).flatMap(([attr, value]) =>
    custom
      ? customSpread(spec, attr, value, modelled)
      : [`${objectKey(attr)}: ${attrValue(spec, value, modelled)}`],
  )
  const slot = node.slot === undefined ? [] : [`slot: '${node.slot}'`]
  const handler =
    spec.controlTag === node.tag && modelled && FORM_CONTROLS.has(node.tag) ? ['onInput'] : []
  const props = [...slot, ...entries, ...handler]
  const propsSource = props.length === 0 ? 'null' : `{ ${props.join(', ')} }`
  const children = node.children ?? []
  if (children.length === 0) {
    return `${pad}h('${node.tag}', ${propsSource})`
  }
  const inlineChildren = children.every((child) => !('tag' in child))
  if (inlineChildren && children.length === 1) {
    const only = nodeSource(spec, children[0] ?? { text: '' }, childrenText, modelled, 0)
    return `${pad}h('${node.tag}', ${propsSource}, ${only})`
  }
  return [
    `${pad}h('${node.tag}', ${propsSource}, [`,
    ...children.map((child) => `${nodeSource(spec, child, childrenText, modelled, depth + 1)},`),
    `${pad}])`,
  ].join('\n')
}

const componentFile = (spec: WrapperSpec): GeneratedFile => {
  const childrenText = childrenTextOf(spec)
  const hasSlots =
    childrenText !== undefined || spec.markupProps.some((item) => item.kind === 'raw')
  const modelled = spec.pe === 'A' && FORM_CONTROLS.has(spec.controlTag ?? '')
  const context = [...(hasSlots ? ['slots'] : []), ...(modelled ? ['emit'] : [])]
  const param = context.length === 0 ? '' : `, { ${context.join(', ')} }`
  const tree = nodeSource(
    spec,
    spec.contract?.tree ?? { text: '' },
    childrenText,
    modelled,
    modelled ? 3 : 2,
  )
  const setupLines = modelled
    ? [
        `  (props: ${spec.pascal}Props${param}) => {`,
        '    const onInput = (event: Event): void => {',
        '      const target = event.target',
        // 共通の親（HTMLElement）には `value` が無いので、操作要素を 1 つずつ絞る
        '      if (',
        '        target instanceof HTMLInputElement',
        '        || target instanceof HTMLSelectElement',
        '        || target instanceof HTMLTextAreaElement',
        '      ) {',
        `        emit('update:modelValue', target.value)`,
        '      }',
        '    }',
        '    return () => {',
        ...(spec.idFallback === undefined
          ? []
          : [`      const controlId = props.id ?? props.${spec.idFallback}`]),
        `      return ${tree.trimStart()}`,
        '    }',
        '  },',
      ]
    : [`  (props: ${spec.pascal}Props${param}) => () =>`, `${tree},`]
  const options = [
    '  {',
    `    name: '${spec.pascal}',`,
    `    props: [${propNames(spec, modelled)
      .map((name) => `'${name}'`)
      .join(', ')}],`,
    ...(modelled ? [`    emits: ['update:modelValue'],`] : []),
    '  },',
  ]
  return {
    path: `${spec.name}.ts`,
    content: `${[
      HEADER,
      `import { defineComponent, h } from 'vue'`,
      ...(spec.namedTypes.length > 0
        ? [
            `import type { ${spec.namedTypes.join(', ')} } from '@rimltempest/riml-ds-elements/${spec.subpath}'`,
          ]
        : []),
      '',
      ...propsType(spec, modelled),
      '',
      `export const ${spec.pascal} = defineComponent(`,
      ...setupLines,
      ...options,
      ')',
    ].join('\n')}\n`,
  }
}

const elementsFile = (specs: readonly WrapperSpec[]): GeneratedFile => {
  const imports = specs.flatMap((spec) =>
    spec.namedTypes.length === 0
      ? []
      : [
          `import type { ${spec.namedTypes.join(', ')} } from '@rimltempest/riml-ds-elements/${spec.subpath}'`,
        ],
  )
  // GlobalComponents はプラグインが `app.component()` する部品だけ（experimental は登録しない）。
  // `<rd-*>` を直接書くときの IntrinsicElementAttributes は全部品を持つ（型は害が無い）
  const registered = specs.filter(
    (spec) => spec.contract !== undefined && spec.status !== 'experimental',
  )
  return {
    path: 'elements.ts',
    content: `${[
      HEADER,
      ...imports,
      '',
      `declare module 'vue' {`,
      '  interface GlobalComponents {',
      ...registered.map(
        (spec) => `    ${spec.pascal}: typeof import('./${spec.name}.js')['${spec.pascal}']`,
      ),
      '  }',
      '  /** `<rd-*>` をテンプレートに直接書くときの属性（`isCustomElement` は利用側の設定） */',
      '  interface IntrinsicElementAttributes {',
      ...specs.map((spec) => {
        const own =
          spec.attrs.length === 0
            ? 'Record<string, never>'
            : `{ ${spec.attrs.map((attr) => `${objectKey(attr.name)}?: ${typeText(attr.type)}`).join('; ')} }`
        return `    '${spec.tag}': ${own}`
      }),
      '  }',
      '}',
      '',
      'export {}',
    ].join('\n')}\n`,
  }
}

type IndexOptions = {
  readonly path: string
  readonly bag: string
  readonly comment: string
}

const indexFile = (options: IndexOptions, specs: readonly WrapperSpec[]): GeneratedFile => ({
  path: options.path,
  content: `${[
    HEADER,
    `import './elements.js'`,
    ...specs.map((spec) => `import { ${spec.pascal} } from './${spec.name}.js'`),
    '',
    ...specs.map((spec) => `export type { ${spec.pascal}Props } from './${spec.name}.js'`),
    `export { ${specs.map((spec) => spec.pascal).join(', ')} }`,
    '',
    options.comment,
    `export const ${options.bag} = { ${specs.map((spec) => spec.pascal).join(', ')} }`,
  ].join('\n')}\n`,
})

export const vueFiles = (specs: readonly WrapperSpec[]): readonly GeneratedFile[] => {
  const withMarkup = specs.filter((spec) => spec.contract !== undefined)
  const experimental = withMarkup.filter((spec) => spec.status === 'experimental')
  const stable = withMarkup.filter((spec) => spec.status !== 'experimental')
  return [
    ...withMarkup.map(componentFile),
    elementsFile(specs),
    indexFile(
      {
        path: 'index.ts',
        bag: 'rdComponents',
        comment: '/** プラグインが `app.component()` で登録する stable な部品 */',
      },
      stable,
    ),
    indexFile(
      {
        path: 'experimental.ts',
        bag: 'rdExperimentalComponents',
        comment:
          '/** semver の対象外（ADR-0009）。プラグインは登録しないので、利用側が `app.component()` する */',
      },
      experimental,
    ),
  ]
}
