import { describe, expect, it } from 'vitest'
import { toWrapperSpecs } from '../../src/wrappers/core/common.js'
import { astroExports, astroFiles } from '../../src/wrappers/core/astro.js'
import { contracts, manifest } from './fixtures.js'

const specs = toWrapperSpecs(manifest, contracts)
const files = astroFiles(specs)
const find = (path: string): string => files.find((file) => file.path === path)?.content ?? ''

describe('astroFiles', () => {
  it('契約の木をほぼそのまま HTML にし、props はフロントマターで受ける', () => {
    expect(find('button.astro')).toBe(
      `---
// generated by tools/cem — do not edit（\`bun run gen\`）
import type { ButtonVariant } from '@rimltempest/riml-ds-elements/button'

type Props = {
  variant?: ButtonVariant
  loading?: boolean
  type?: 'button' | 'submit' | 'reset'
  label?: string
  class?: string
}

const { variant, loading, type, label, class: className } = Astro.props
---

<rd-button variant={variant} loading={loading || undefined} class={className}>
  <button type={type}><slot>{label}</slot></button>
</rd-button>
`,
    )
  })

  it('ティア B の raw は <slot /> になる', () => {
    const source = find('dialog.astro')
    expect(source).toContain('<h2 slot="label">{label}</h2>')
    expect(source).toContain('<slot />')
  })

  it('text-field は id が無ければ name を使う', () => {
    const source = find('text-field.astro')
    expect(source).toContain('const controlId = id ?? name')
    expect(source).toContain('<label for={controlId}>{label}</label>')
    expect(source).toContain('value={defaultValue}')
  })

  it('名前つきの raw は名前つきの <slot> になり、既定 slot に潰れない', () => {
    const source = find('experimental/menu.astro')
    expect(source).toContain('<slot name="trigger" />')
    expect(source).toContain('<slot name="items" />')
    expect(source).not.toContain('<slot />')
  })

  it('experimental の部品は experimental/ の下に出る', () => {
    expect(files.some((file) => file.path === 'select.astro')).toBe(false)
    expect(find('experimental/select.astro')).toContain('<rd-select')
  })

  it('ティア C は .astro を持たない（JS 無しで意味が無い）', () => {
    expect(files.some((file) => file.path === 'live-region.astro')).toBe(false)
    expect(files.map((file) => file.path)).toEqual([
      'button.astro',
      'dialog.astro',
      'experimental/menu.astro',
      'experimental/select.astro',
      'text-field.astro',
      'experimental/toggle.astro',
    ])
  })
})

describe('astroExports', () => {
  it('契約のある部品を stable → experimental の順で公開する', () => {
    expect(astroExports(specs)).toEqual({
      '.': { types: './dist/index.d.ts', default: './dist/index.js' },
      './button.astro': './src/generated/button.astro',
      './dialog.astro': './src/generated/dialog.astro',
      './text-field.astro': './src/generated/text-field.astro',
      './experimental/menu.astro': './src/generated/experimental/menu.astro',
      './experimental/select.astro': './src/generated/experimental/select.astro',
      './experimental/toggle.astro': './src/generated/experimental/toggle.astro',
      './package.json': './package.json',
    })
  })

  it('キーの並びが決まっている（生成が冪等になる）', () => {
    expect(Object.keys(astroExports(specs))).toEqual([
      '.',
      './button.astro',
      './dialog.astro',
      './text-field.astro',
      './experimental/menu.astro',
      './experimental/select.astro',
      './experimental/toggle.astro',
      './package.json',
    ])
  })

  it('契約を持たないティア C は公開しない', () => {
    expect(Object.keys(astroExports(specs))).not.toContain('./live-region.astro')
  })
})
