import { describe, expect, it } from 'vitest'
import { toWrapperSpecs } from '../../src/wrappers/core/common.js'
import { astroFiles } from '../../src/wrappers/core/astro.js'
import { contracts, manifest } from './fixtures.js'

const files = astroFiles(toWrapperSpecs(manifest, contracts))
const find = (path: string): string => files.find((file) => file.path === path)?.content ?? ''

describe('astroFiles', () => {
  it('契約の木をほぼそのまま HTML にし、props はフロントマターで受ける', () => {
    expect(find('button.astro')).toBe(
      `---
// generated by tools/cem — do not edit（\`bun run gen\`）
import type { ButtonVariant } from '@rimltempest/riml-ds-elements/button'

type Props = {
  variant?: ButtonVariant
  loading?: boolean
  type?: 'button' | 'submit' | 'reset'
  label?: string
  class?: string
}

const { variant, loading, type, label, class: className } = Astro.props
---

<rd-button variant={variant} loading={loading || undefined} class={className}>
  <button type={type}><slot>{label}</slot></button>
</rd-button>
`,
    )
  })

  it('ティア B の raw は <slot /> になる', () => {
    const source = find('dialog.astro')
    expect(source).toContain('<h2 slot="label">{label}</h2>')
    expect(source).toContain('<slot />')
  })

  it('text-field は id が無ければ name を使う', () => {
    const source = find('text-field.astro')
    expect(source).toContain('const controlId = id ?? name')
    expect(source).toContain('<label for={controlId}>{label}</label>')
    expect(source).toContain('value={defaultValue}')
  })

  it('experimental の部品は experimental/ の下に出る', () => {
    expect(files.some((file) => file.path === 'select.astro')).toBe(false)
    expect(find('experimental/select.astro')).toContain('<rd-select')
  })

  it('ティア C は .astro を持たない（JS 無しで意味が無い）', () => {
    expect(files.some((file) => file.path === 'live-region.astro')).toBe(false)
    expect(files.map((file) => file.path)).toEqual([
      'button.astro',
      'dialog.astro',
      'experimental/select.astro',
      'text-field.astro',
    ])
  })
})
