import { describe, expect, it } from 'vitest'
import { toWrapperSpecs } from '../../src/wrappers/core/common.js'
import { reactFiles } from '../../src/wrappers/core/react.js'
import { contracts, manifest } from './fixtures.js'

const files = reactFiles(toWrapperSpecs(manifest, contracts))
const find = (path: string): string => files.find((file) => file.path === path)?.content ?? ''

describe('reactFiles', () => {
  it('ティア A の既定部品は契約の木をそのまま JSX にする', () => {
    expect(find('button.tsx')).toBe(
      `// generated by tools/cem — do not edit（\`bun run gen\`）
import type { ReactNode, Ref } from 'react'
import type { ButtonVariant } from '@rimltempest/riml-ds-elements/button'

export type RdButtonProps = {
  readonly variant?: ButtonVariant | undefined
  readonly loading?: boolean | undefined
  readonly type?: 'button' | 'submit' | 'reset' | undefined
  readonly label?: ReactNode | undefined
  readonly children?: ReactNode
  readonly className?: string | undefined
  readonly ref?: Ref<HTMLElement> | undefined
}

export const RdButton = ({
  variant,
  loading,
  type,
  label,
  children,
  className,
  ref,
}: RdButtonProps): ReactNode => (
  <rd-button ref={ref} variant={variant} loading={loading || undefined} className={className}>
    <button type={type}>{children ?? label}</button>
  </rd-button>
)
`,
    )
  })

  it('text-field は for/value/autocomplete を React の綴りに直し、id を name で代替する', () => {
    const source = find('text-field.tsx')
    expect(source).toContain('const controlId = id ?? name')
    expect(source).toContain('<label htmlFor={controlId}>{label}</label>')
    expect(source).toContain('defaultValue={defaultValue}')
    expect(source).toContain('autoComplete={autocomplete}')
    expect(source).toContain('required={required || undefined}')
    // ティア A の controlled / uncontrolled はネイティブ側で受ける（ADR-0012 §5）
    expect(source).toContain('onInput={onInput}')
  })

  it('ティア B の raw は children（ReactNode）になり、slot 属性を保つ', () => {
    const source = find('dialog.tsx')
    expect(source).toContain('readonly children: ReactNode')
    expect(source).toContain('<h2 slot="label">{label}</h2>')
    expect(source).toContain('{children}')
    expect(source).not.toContain('dangerouslySetInnerHTML')
  })

  it("既定 export には 'use client' が無く、client/ には有る", () => {
    const markupFiles = files.filter(
      (file) => !file.path.startsWith('client/') && file.path.endsWith('.tsx'),
    )
    expect(markupFiles.map((file) => file.path)).toEqual([
      'button.tsx',
      'dialog.tsx',
      'text-field.tsx',
    ])
    for (const file of markupFiles) {
      expect(file.content).not.toContain('use client')
    }
    const clientFiles = files.filter((file) => file.path.startsWith('client/'))
    expect(clientFiles.length).toBeGreaterThan(0)
    for (const file of clientFiles) {
      expect(file.content.startsWith("'use client'\n")).toBe(true)
    }
  })

  it('ティア C は既定 export に出ず、client にだけ出る', () => {
    expect(find('index.ts')).not.toContain('live-region')
    expect(find('client.ts')).toContain("export { RdLiveRegion } from './client/live-region.js'")
    expect(files.some((file) => file.path === 'live-region.tsx')).toBe(false)
  })

  it('client ラッパーは rd-* を addEventListener で受け、controlled を再同期する', () => {
    expect(find('client/button.tsx')).toContain("useRdEvent(host, 'rd-press', onRdPress)")
    expect(find('client/button.tsx')).toContain(
      'readonly onRdPress?: ((event: CustomEvent<Record<string, never>>) => void) | undefined',
    )
    const textField = find('client/text-field.tsx')
    expect(textField).toContain('useLayoutEffect')
    expect(textField).toContain("host.current?.querySelector('input')")
    expect(textField).toContain('defaultValue={value ?? defaultValue}')
    // 親が値を拒否したときも効果が走るよう入力のたびに描き直す
    expect(textField).toContain('const [, bump] = useReducer((count: number) => count + 1, 0)')
    expect(textField).toContain('onInput?.(event)')
    // rest 要素の後ろにカンマを置くと構文エラーになる
    expect(textField).not.toContain('...rest,')
  })

  it('jsx の型は rd-* を IntrinsicElements に足す', () => {
    const source = find('jsx.ts')
    expect(source).toContain("declare module 'react'")
    expect(source).toContain("'rd-button': RdElementAttrs<{ variant?: ButtonVariant | undefined")
    expect(source).toContain("'rd-live-region': RdElementAttrs<unknown>")
  })

  it('生成物の一覧が決まっている（冪等の前提）', () => {
    expect(files.map((file) => file.path)).toEqual([
      'button.tsx',
      'dialog.tsx',
      'text-field.tsx',
      'client/internal.ts',
      'client/button.tsx',
      'client/dialog.tsx',
      'client/live-region.tsx',
      'client/text-field.tsx',
      'jsx.ts',
      'index.ts',
      'client.ts',
    ])
  })
})
