import { describe, expect, it } from 'vitest'
import { toWrapperSpecs } from '../../src/wrappers/core/common.js'
import { svelteFiles } from '../../src/wrappers/core/svelte.js'
import { contracts, manifest } from './fixtures.js'

const files = svelteFiles(toWrapperSpecs(manifest, contracts))
const find = (path: string): string => files.find((file) => file.path === path)?.content ?? ''

describe('svelteFiles', () => {
  it('契約の木を Svelte 5 の $props() 部品にする', () => {
    expect(find('button.svelte')).toBe(
      `<!-- generated by tools/cem — do not edit（\`bun run gen\`） -->
<script>
  let { variant, loading, type, label, children, class: className } = $props()
</script>

<rd-button
  {...(variant === undefined ? {} : { variant })}
  {...(loading === true ? { loading } : {})}
  {...(className === undefined ? {} : { class: className })}
>
  <button {type}>{#if children}{@render children()}{:else}{label}{/if}</button>
</rd-button>
`,
    )
  })

  it('text-field は id が無ければ name を使い、value を defaultValue から出す', () => {
    const source = find('text-field.svelte')
    expect(source).toContain('const controlId = $derived(id ?? name)')
    expect(source).toContain('<label for={controlId}>{label}</label>')
    expect(source).toContain('value={defaultValue}')
    expect(source).toContain('required={required || undefined}')
  })

  it('ティア B の raw は {@render children()} になる', () => {
    const source = find('dialog.svelte')
    expect(source).toContain('<h2 slot="label">{label}</h2>')
    expect(source).toContain('{@render children()}')
    expect(source).not.toContain('{@html')
  })

  it('型は svelteHTML を広げ、rd-* のイベントは onrd-* で受ける', () => {
    expect(files.some((file) => file.path === 'live-region.svelte')).toBe(false)
    const source = find('elements.d.ts')
    expect(source).toContain('declare namespace svelteHTML')
    expect(source).toContain(`'onrd-press'?: (event: CustomEvent<Record<string, never>>) => void`)
    expect(source).toContain(`'rd-live-region':`)
    expect(find('index.js')).toContain(`export { default as RdButton } from './button.svelte'`)
  })
})
