import { describe, expect, it } from 'vitest'
import { toWrapperSpecs } from '../../src/wrappers/core/common.js'
import { svelteFiles } from '../../src/wrappers/core/svelte.js'
import { contracts, manifest } from './fixtures.js'

const files = svelteFiles(toWrapperSpecs(manifest, contracts))
const find = (path: string): string => files.find((file) => file.path === path)?.content ?? ''

describe('svelteFiles', () => {
  it('契約の木を Svelte 5 の $props() 部品にする', () => {
    expect(find('button.svelte')).toBe(
      `<!-- generated by tools/cem — do not edit（\`bun run gen\`） -->
<script>
  let { variant, loading, type, label, children, class: className } = $props()
</script>

<rd-button
  {...(variant === undefined ? {} : { variant })}
  {...(loading === true ? { loading } : {})}
  {...(className === undefined ? {} : { class: className })}
>
  <button {type}>{#if children}{@render children()}{:else}{label}{/if}</button>
</rd-button>
`,
    )
  })

  it('text-field は id が無ければ name を使い、value を defaultValue から出す', () => {
    const source = find('text-field.svelte')
    expect(source).toContain('const controlId = $derived(id ?? name)')
    expect(source).toContain('<label for={controlId}>{label}</label>')
    expect(source).toContain('value={defaultValue}')
    expect(source).toContain('required={required || undefined}')
  })

  it('ティア B の raw は {@render children()} になる', () => {
    const source = find('dialog.svelte')
    expect(source).toContain('<h2 slot="label">{label}</h2>')
    expect(source).toContain('{@render children()}')
    expect(source).not.toContain('{@html')
  })

  it('名前つきの raw は名前つきの snippet になり、既定 slot に潰れない', () => {
    const source = find('menu.svelte')
    expect(source).toContain('{@render trigger?.()}')
    expect(source).toContain('{@render items?.()}')
    expect(source).not.toContain('{@render children()}')
  })

  it('experimental の部品は root の index に出ず、./experimental の index に出る', () => {
    expect(find('index.js')).not.toContain('RdSelect')
    expect(find('experimental.js')).toBe(
      `// generated by tools/cem — do not edit（\`bun run gen\`）
export { default as RdMenu } from './menu.svelte'
export { default as RdSelect } from './select.svelte'
export { default as RdToggle } from './toggle.svelte'
`,
    )
  })

  it('型は svelteHTML を広げ、rd-* のイベントは onrd-* で受ける', () => {
    expect(files.some((file) => file.path === 'live-region.svelte')).toBe(false)
    const source = find('elements.d.ts')
    expect(source).toContain('declare namespace svelteHTML')
    expect(source).toContain(`'onrd-press'?: (event: CustomEvent<Record<string, never>>) => void`)
    expect(source).toContain(`'rd-live-region':`)
    expect(find('index.js')).toContain(`export { default as RdButton } from './button.svelte'`)
  })

  it('ハイフンを含むホスト属性はオブジェクトのキーと svelteHTML の型で引用する', () => {
    const source = find('note.svelte')
    expect(source).toContain(`{...(emptyText === undefined ? {} : { 'empty-text': emptyText })}`)
    expect(source).not.toContain('{ empty-text:')
    const types = find('elements.d.ts')
    expect(types).toContain(`      'empty-text'?: string`)
  })
})
