// 強制配色モード（@media (forced-colors: active)）ではシステム色だけを使う。
// stylelint-declaration-strict-value は「properties 配列のどの項目に当たったか」で
// ignoreValues のキーを引くため、`/color$/` だけでなく色を扱う各リテラル
// プロパティにも同じ一覧を割り当てる必要がある。
const colorKeywords = [
  'inherit',
  'currentColor',
  'transparent',
  'Canvas',
  'CanvasText',
  'LinkText',
  'VisitedText',
  'ActiveText',
  'ButtonFace',
  'ButtonText',
  'ButtonBorder',
  'Field',
  'FieldText',
  'Highlight',
  'HighlightText',
  'SelectedItem',
  'SelectedItemText',
  'Mark',
  'MarkText',
  'GrayText',
  'AccentColor',
  'AccentColorText',
]

/** @type {import('stylelint').Config} */
export default {
  extends: ['stylelint-config-standard'],
  plugins: ['stylelint-declaration-strict-value'],
  overrides: [{ files: ['**/*.ts'], customSyntax: 'postcss-lit' }],
  rules: {
    // 生値禁止。色・寸法・字・影・時間・角丸は var(--rd-*) だけ（ADR-0004）
    'scale-unlimited/declaration-strict-value': [
      [
        '/color$/',
        'fill',
        'stroke',
        'background',
        'background-color',
        'border',
        'border-color',
        'outline-color',
        'box-shadow',
        'font-family',
        'font-size',
        'font-weight',
        'line-height',
        'border-radius',
        'z-index',
        'transition-duration',
        'animation-duration',
        'transition-timing-function',
        'animation-timing-function',
        '/^(padding|margin|gap|inset|top|right|bottom|left)/',
        'width',
        'height',
        'min-width',
        'min-height',
        'max-width',
        'max-height',
      ],
      {
        ignoreValues: {
          '': [
            'inherit',
            'initial',
            'unset',
            'revert',
            'revert-layer',
            'currentColor',
            'transparent',
            'none',
            'auto',
            '0',
            '100%',
            'fit-content',
            'max-content',
            'min-content',
            '1px',
            '-1px',
          ],
          '/color$/': colorKeywords,
          background: colorKeywords,
          'background-color': colorKeywords,
          border: colorKeywords,
          'border-color': colorKeywords,
          'outline-color': colorKeywords,
          'box-shadow': colorKeywords,
          fill: colorKeywords,
          stroke: colorKeywords,
          'font-weight': ['inherit', 'bolder', 'lighter'],
          'z-index': ['auto', '-1', '0', '1'],
          'line-height': ['normal', 'inherit', '1'],
          '/^(padding|margin|gap|inset|top|right|bottom|left)/': ['auto', '0', 'inherit'],
          '/^(min-|max-)?(width|height)$/': [
            'auto',
            '0',
            '100%',
            '100vw',
            '100dvh',
            'fit-content',
            'max-content',
            'min-content',
            'inherit',
            '100cqi',
            '100cqb',
          ],
        },
        ignoreFunctions: true, // var() / light-dark() / clamp() / calc() を許す
        expandShorthand: true,
      },
    ],
    // 物理プロパティ禁止 → 論理プロパティ（RTL、ADR-0004）。width/height は inline-size/block-size に寄せる
    'property-disallowed-list': [
      'margin-left',
      'margin-right',
      'padding-left',
      'padding-right',
      'border-left',
      'border-right',
      'left',
      'right',
      'text-align',
      'float',
      'width',
      'height',
      'min-width',
      'min-height',
      'max-width',
      'max-height',
    ],
    'unit-disallowed-list': [
      ['px'],
      {
        ignoreProperties: {
          px: ['outline-width', 'border-width', 'outline-offset', 'border', 'outline'],
        },
      },
    ],
    'selector-max-id': 0,
    'selector-max-specificity': '0,3,0',
    'declaration-no-important': true,
    'media-feature-range-notation': 'context',
    'color-function-notation': 'modern',
    'color-no-hex': true,
    'custom-property-pattern': ['^rd-[a-z0-9-]+$', { message: 'CSS 変数は --rd- で始める' }],
    'selector-class-pattern': null,
    'no-descending-specificity': null,
    'import-notation': 'string',
  },
  ignoreFiles: ['**/dist/**', '**/node_modules/**', '**/*.d.ts'],
}
