/** 部品の define。**ハイドレーションの後**に読む（ティア A は light DOM に強化ノードを足す） */
import '@rimltempest/riml-ds-elements/button/define'
import '@rimltempest/riml-ds-elements/experimental/checkbox/define'
import '@rimltempest/riml-ds-elements/experimental/menu/define'
import '@rimltempest/riml-ds-elements/experimental/meter/define'
import '@rimltempest/riml-ds-elements/experimental/popover/define'
import '@rimltempest/riml-ds-elements/experimental/radio-group/define'
import '@rimltempest/riml-ds-elements/experimental/select/define'
import '@rimltempest/riml-ds-elements/experimental/slider/define'
import '@rimltempest/riml-ds-elements/experimental/tabs/define'
import '@rimltempest/riml-ds-elements/experimental/window/define'
import '@rimltempest/riml-ds-elements/dialog/define'
import '@rimltempest/riml-ds-elements/live-region/define'
import '@rimltempest/riml-ds-elements/text-field/define'
